-- SCRIPT TO INSERT SEARCH QUERY
-- VIETLP
IF OBJECT_ID('[SP_LOAD_SEARCH_QUERY_STATISTIC]', 'P') IS NOT NULL
	DROP PROCEDURE SP_LOAD_SEARCH_QUERY_STATISTIC
GO

CREATE PROCEDURE SP_LOAD_SEARCH_QUERY_STATISTIC
(
	@From_Date DATETIME,
	@To_Date DATETIME
)
AS
BEGIN
	SELECT sd.Sentence, sd.Search_Date, sd.Result_Count
	FROM SentenceDictionary sd
	WHERE sd.Search_Date BETWEEN @From_Date AND @To_Date
	GROUP BY sd.Sentence, sd.Search_Date, sd.Result_Count
	ORDER BY sd.Search_Date DESC
END