-- SCRIPT TO INSERT SEARCH QUERY
-- VIETLP
IF OBJECT_ID('[SP_LOAD_SEARCH_QUERY_STATISTIC]', 'P') IS NOT NULL
	DROP PROCEDURE SP_LOAD_SEARCH_QUERY_STATISTIC
GO

CREATE PROCEDURE SP_LOAD_SEARCH_QUERY_STATISTIC
(
	@From_Date DATETIME,
	@To_Date DATETIME
)
AS
BEGIN
	SELECT sq.Sentence, sq.Search_Time_Count, sq.Result_Count
	FROM SearchQuery sq
	WHERE sq.Search_Date BETWEEN @From_Date AND @To_Date
	ORDER BY sq.Search_Time_Count DESC, sq.Result_Count DESC
END

EXEC SP_LOAD_SEARCH_QUERY_STATISTIC '1900-12-31', '2015-12-31'