-- FUNCTION TO CALCULATE AVERAGE RATING SCORE OF A SPECIFIC HOSPITAL
-- SONNX
IF OBJECT_ID('[FU_CALCULATE_AVERAGE_RATING]', 'FN') IS NOT NULL
	DROP FUNCTION [FU_CALCULATE_AVERAGE_RATING]
GO
CREATE FUNCTION [dbo].[FU_CALCULATE_AVERAGE_RATING]
(
	@HospitalID INT
)
RETURNS FLOAT
AS
BEGIN
	DECLARE @TotalRecord INT

	SELECT @TotalRecord = r.Total
	FROM (SELECT COUNT(Rating_ID) AS Total
		  FROM Rating
		  WHERE Hospital_ID = @HospitalID) r

	DECLARE @AverageScore FLOAT 

	SELECT @AverageScore = a.Result
	FROM (SELECT CONVERT(FLOAT, (CONVERT(FLOAT, SUM(Score)) / @TotalRecord)) AS Result
		  FROM Rating
		  WHERE Hospital_ID = @HospitalID) a

	RETURN @AverageScore
END