-- SPLIT WORDS IN A STRING INTO LIST OF TOKENS
-- RETURN TABLE THAT CONTAINS LIST OF TOKENS
-- SONNX
IF OBJECT_ID('[FU_STRING_TOKENIZE]', 'F') IS NOT NULL
	DROP FUNCTION FU_STRING_TOKENIZE
GO
CREATE FUNCTION [dbo].[FU_STRING_TOKENIZE]
(
	@InputStr NVARCHAR(MAX),
	@Delimeter VARCHAR(1)
)
RETURNS @TokenList TABLE (ID INT PRIMARY KEY,
						  Token NVARCHAR(32))
AS
BEGIN
	DECLARE @Token NVARCHAR(32)
	DECLARE @Position INT
	DECLARE @Id INT = 1

	WHILE CHARINDEX(@Delimeter, @InputStr) > 0
	BEGIN
		SELECT @Position = CHARINDEX(@Delimeter, @InputStr)
		SELECT @Token = SUBSTRING(@InputStr, 1, @Position - 1)

		INSERT INTO @TokenList 
		SELECT @Id, @Token

		SELECT @InputStr = SUBSTRING(@InputStr, @Position + 1, LEN(@InputStr) - @Position)
		SET @Id += 1
	END

	INSERT INTO @TokenList 
	SELECT @Id, @InputStr

	RETURN
END