-- FUNCTION TO TAKE THE FIRST CHARACTER OF EACH WORD IN A STRING
-- SONNX
IF OBJECT_ID('[[FU_TAKE_FIRST_CHARACTER_OF_EACH_WORD_IN_STRING]]', 'F') IS NOT NULL
	DROP FUNCTION [FU_TAKE_FIRST_CHARACTER_OF_EACH_WORD_IN_STRING]
GO
CREATE FUNCTION [dbo].[FU_TAKE_FIRST_CHARACTER_OF_EACH_WORD_IN_STRING]
(
	@InputStr NVARCHAR(4000)
)
RETURNS NVARCHAR(4000)
AS
BEGIN
	DECLARE @TempStr NVARCHAR(1)
	SET @TempStr = '';

	DECLARE @Counter INT
	SET @Counter = 1

	WHILE (@Counter <= LEN(@InputStr))
	BEGIN
		SET @Counter = 1
		SET @TempStr = @TempStr + SUBSTRING(@TempStr, 1, 1)
		SET @Counter = @Counter + 1
	END
END