--VIETLP--
IF OBJECT_ID('[SP_LOAD_HOSPITAL_TYPE_COUNT]', 'P') IS NOT NULL
	DROP PROCEDURE SP_LOAD_HOSPITAL_TYPE_COUNT
GO
CREATE PROCEDURE SP_LOAD_HOSPITAL_TYPE_COUNT
AS
BEGIN
	SELECT ht.Type_ID, ht.Type_Name, COUNT(*) AS HospitalType_Count
	FROM HospitalType ht
	LEFT JOIN Hospital h ON h.Hospital_Type = ht.Type_ID
	GROUP BY ht.Type_ID, ht.Type_Name
END

EXEC SP_LOAD_HOSPITAL_TYPE_COUNT