-- SCRIPT TO LOAD A SPECIFIC DISTRICT BASE ON CITI_ID
-- SONNX
IF OBJECT_ID('[SP_LOAD_CITY_LIST]', 'P') IS NOT NULL
	DROP PROCEDURE [SP_LOAD_CITY_LIST]
GO
CREATE PROCEDURE [dbo].[SP_LOAD_CITY_LIST]
AS
BEGIN
	SELECT City_ID, City_Name
	FROM City
END

-- SCRIPT TO LOAD ALL DISTRICTS BASE ON CITY
-- SONNX
IF OBJECT_ID('[SP_LOAD_DISTRICT_LIST]', 'P') IS NOT NULL
	DROP PROCEDURE [SP_LOAD_DISTRICT_LIST]
GO
CREATE PROCEDURE [dbo].[SP_LOAD_DISTRICT_LIST]
	@CityID INT
AS
BEGIN
	SELECT District_ID, District_Name
	FROM District
	WHERE City_ID = @CityID
END

-- SCRIPT TO LOAD ALL DISEASES BASE ON SPECILITY
-- SONNX
IF OBJECT_ID('SP_LOAD_DISEASE_LIST', 'P') IS NOT NULL
	DROP PROCEDURE SP_LOAD_DISEASE_LIST
GO
CREATE PROCEDURE [dbo].[SP_LOAD_DISEASE_LIST]
	@SpecialityID INT
AS
BEGIN
	SELECT do.Disease_ID, do.Disease_Name
	FROM Disease do, Speciality_Disease sd
	WHERE sd.Speciality_ID = @SpecialityID AND
		  do.Disease_ID = sd.Disease_ID	  
END

-- SCRIPT TO LOAD ALL SPECIALITIES
-- SONNX
IF OBJECT_ID('[SP_LOAD_SPECIALITY_LIST]', 'P') IS NOT NULL
	DROP PROCEDURE [SP_LOAD_SPECIALITY_LIST]
GO
CREATE PROCEDURE [dbo].[SP_LOAD_SPECIALITY_LIST]
AS
BEGIN
	SELECT Speciality_ID, Speciality_Name
	FROM Speciality
END

