-- FUNCTION TO CALCULATE RADIUS
-- VIETLP
IF OBJECT_ID('FU_GET_RADIUS', 'F') IS NOT NULL
	DROP FUNCTION FU_GET_RADIUS
GO
CREATE FUNCTION [dbo].[FU_GET_RADIUS]
(
	@Value FLOAT
)
RETURNS FLOAT
AS
BEGIN
	DECLARE @Result FLOAT
	SET @Result = (@Value * PI()) / 180

	RETURN @Result
END