-- FUNCTION TO REMOVE ALL WHITE SPACES IN A STRING
-- SONNX
IF OBJECT_ID('[FU_REMOVE_WHITE_SPACE]', 'F') IS NOT NULL
	DROP FUNCTION FU_REMOVE_WHITE_SPACE
GO
CREATE FUNCTION [dbo].[FU_REMOVE_WHITE_SPACE]
(
	@InputString NVARCHAR(4000)
)
RETURNS NVARCHAR(4000)
AS
BEGIN
	SET @InputString = REPLACE(@InputString, ' ', '')
	RETURN @InputString
END