-- FUNCTION TO RETURN RATING POINT OF A SPECIFIC HOSPITAL
-- SONNX
IF OBJECT_ID('FU_TAKE_RATING_COUNT', 'FN') IS NOT NULL
	DROP FUNCTION [FU_TAKE_RATING_COUNT]
GO
CREATE FUNCTION [dbo].[FU_TAKE_RATING_COUNT]
(
	@HospitalID INT
)
RETURNS FLOAT
AS
BEGIN
	DECLARE @RatingCount FLOAT

	SELECT @RatingCount = (SELECT h.Rating_Count
						   FROM Hospital h
						   WHERE h.Hospital_ID = @HospitalID)
	IF (@RatingCount IS NULL)
		RETURN 0;
	ELSE
		RETURN @RatingCount;

	RETURN 0;
END