-- TAKE PAIRS OF LETTERS IN A WORD
-- SONNX
IF OBJECT_ID('FU_TAKE_PAIRS_OF_LETTER', 'FN') IS NOT NULL
	DROP FUNCTION FU_TAKE_PAIRS_OF_LETTER
GO
CREATE FUNCTION [dbo].[FU_TAKE_PAIRS_OF_LETTER]
(
	@Word NVARCHAR(32)
)
RETURNS @PairList TABLE (ID INT PRIMARY KEY,
						 Pair NVARCHAR(512))
AS
BEGIN
	DECLARE @Pair NVARCHAR(32)
	DECLARE @NumOfPairs INT = LEN(@Word) - 1
	DECLARE @Count INT = 0

	WHILE (@Count < @NumOfPairs)
	BEGIN
		SET @Pair = SUBSTRING(@Word, @Count + 1, 2)

		INSERT INTO @PairList 
		SELECT @Count + 1, @Pair

		SET @Count += 1
	END

	RETURN
END