-- SCRIPT DEFINE SERVICES FOR HOSPITAL

INSERT INTO [Service] VALUES
	(N'Đăng ký bảo hiệm y tế', 1),
	(N'Khám bệnh bảo hiểm y tế', 1),
	(N'Khám bệnh dịch vụ', 1),
	(N'Khám sức khỏe tổng quát', 1),
	(N'Cấp cứu khẩn cấp', 1),
	(N'Tiếp nhận bệnh nhân mới', 1),
	(N'Chấp nhận bệnh nhân chuyển lên từ tuyến dưới', 1),
	(N'Chăm sóc thay thế cho thân nhân', 6),
	(N'Nút bấm gọi khẩn cấp', 2),
	(N'Bình dưỡng khí', 2),
	(N'Cho phép thú nuôi', 2),
	(N'Cho phép tự nấu nướng', 2),
	(N'Bảo vệ an ninh', 4),
	(N'Truyền thông đa phương tiện', 5),
	(N'Dễ tiếp cận các phương tiện công cộng', 3),
	(N'Xe đưa đón tận nhà', 3),
	(N'Kết nối Internet', 3),
	(N'Chăm sóc y tế tại gia', 5),
	(N'Theo dõi từ xa qua hệ thống máy quay', 6),
	(N'Tư vấn chế độ ăn uống', 4),
	(N'Kiểm tra tình hình sức khỏe định kỳ', 6),
	(N'Chăm sóc cho người già', 6),
	(N'Chăm sóc nhà cửa và các dịch vụ liên quan', 6),
	(N'TV riêng', 6),
	(N'Tủ lạnh riêng', 2),
	(N'Điều hòa', 2),
	(N'Phòng vệ sinh riêng', 2),
	(N'Đường dây điện thoại riêng', 2),
	(N'Phục vụ đồ ăn sáng, trưa, tối', 2),
	(N'Liên lạc trực tiếp với nhân viên trực', 2),
	(N'Đặt lịch khám qua tổng đài 1080', 1),
	(N'Đặt lịch khám qua mạng', 1)