-- SCRIPT TO CREATE SPECIALITIES OF HOSPITALS

INSERT INTO Speciality VALUES
	(N'Bệnh tình dục'),
	(N'Bệnh truyền nhiễm'),
	(N'Cấp cứu'),
	(N'Chấn thương chỉnh hình'),
	(N'Chuẩn đoán hình ảnh'),
	(N'Da liễu'),
	(N'Di truyền'),
	(N'Điều dưỡng'),
	(N'Dinh dưỡng'),
	(N'Dược'),
	(N'Gây mê'),
	(N'Hô hấp'),
	(N'Hóa sinh'),
	(N'Hồi sức'),
	(N'Huyết học'),
	(N'Nam khoa'),
	(N'Ngoại hô hấp'),
	(N'Ngoại tổng hợp'),
	(N'Ngoại tổng quát'),
	(N'Nha khoa'),
	(N'Nhi khoa'),
	(N'Nội tiết'),
	(N'Nội tim mạch'),
	(N'Nội tổng hợp'),
	(N'Nội tổng quát'),
	(N'Phẫu thuật thẩm mỹ'),
	(N'Phẫu thuật'),
	(N'Phục hồi chức năng'),
	(N'Răng - Hàm - Mặt'),
	(N'Sản phụ - Phụ khoa'),
	(N'Tai - Mũi - Họng'),
	(N'Thần kinh'),
	(N'Tiết niệu'),
	(N'Tiêu hóa - Gan - Mật'),
	(N'Tiêu hóa'),
	(N'Tim mạch'),
	(N'Tư vấn tâm lý - Tâm thần'),
	(N'Ung bướu'),
	(N'Vật lý trị liệu'),
	(N'Vi sinh'),
	(N'Vi sinh'),
	(N'Xét nghiệm'),
	(N'Xét nghiệm'),
	(N'Xương khớp'),
	(N'Y học cổ truyền'),
	(N'Y học hạt nhân'),
	(N'Y học thể thao')